CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TYPE business_type AS ENUM (
    'restaurant/bar', 
    'shopping', 
    'hotel/accommodations', 
    'service', 
    'housing/realty', 
    'education', 
    'healthcare'
);

CREATE TYPE state_district_territory AS ENUM (
    'AK',
    'AL',
    'AR',
    'AZ',
    'CA',
    'CO',
    'CT',
    'DE',
    'FL',
    'GA',
    'HI',
    'IA',
    'ID',
    'IL',
    'IN',
    'KS',
    'KY'
    'LA',
    'MA',
    'MD',
    'ME',
    'MI',
    'MN',
    'MO',
    'MS',
    'MT',
    'NC'
    'ND',
    'NE',
    'NH',
    'NJ',
    'NM',
    'NV',
    'NY',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VA',
    'VT',
    'WA',
    'WI',
    'WV',
    'WY',
    'DC',
    'AS',
    'GU',
    'MP',
    'PR',
    'VI'
);

CREATE TABLE businesses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category business_type NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state state_district_territory NOT NULL,
    -- zipcode ,
    website VARCHAR(255)
);

CREATE TYPE identity_group AS ENUM (
    'Black, Asian/Pacific Islander, Latinx, and Indigenous persons',
    'Disabled persons',    
    'Migrants/Immigrants',
    'LGBTQIA',
    'Women'
);

CREATE TABLE reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reviewer_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    business_id INTEGER REFERENCES businesses(id) ON DELETE CASCADE NOT NULL,
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    friendly_for identity_group NOT NULL,
    rating INTEGER NOT NULL,
    review VARCHAR(255) NOT NULL
);

CREATE TABLE saved_businesses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    business_id INTEGER REFERENCES businesses(id) ON DELETE CASCADE NOT NULL
);