DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS businesses CASCADE;

DROP TYPE IF EXISTS state_district_territory CASCADE;

DROP TYPE IF EXISTS business_type CASCADE;

DROP TYPE IF EXISTS identity_group CASCADE;

DROP TABLE IF EXISTS reviews CASCADE;

DROP TABLE IF EXISTS saved_businesses CASCADE;